version: "3.8"

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    command: npm start
    volumes:
      - .:/app
    ports:
      - 80:3000
    depends_on: 
      - db
      - cache

  db:
    image: mongo:4.2
    restart: always
    volumes:
      - .dbdata:/data/db
    ports:
      - 27017:27017

  cache:
    image: redis:6-alpine
    command: redis-server
    volumes:
      - .cachedata:/data
    ports:
      - "6379:6379"