version: "3.8"

services:
  backend:
    restart: always
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - 3001:3000
    env_file: .env.dev
    environment: 
      NODE_ENV: development
      DEBUG: adwiarifin-nodemicro:*
    depends_on: 
      - db
      - cache

  db:
    image: mongo:4.2
    restart: always
    volumes:
      - .dbdata:/data/db
    ports:
      - 27018:27017

  cache:
    image: redis:6-alpine
    restart: always
    command: redis-server
    volumes:
      - .cachedata:/data
    ports:
      - "6380:6379"