version: "3.8"

services:
  backend:
    restart: always
    build:
      context: .
      target: prod
    command: npm start
    ports:
      - 80:3000
    depends_on: 
      - db
      - cache

  db:
    image: mongo:4.2
    restart: always

  cache:
    image: redis:6-alpine
    restart: always
    command: redis-server