version: "3.8"

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - 3001:3000
    env_file: 
      - .env.dev
    depends_on: 
      - db

  db:
    image: mongo:4.2
    restart: always
    volumes:
      - .dbdata:/data/db
    ports:
      - 27018:27017